
$mod = SUPER
$terminal = alacritty
env = HYPRCURSOR_THEME,{{cursor_theme_name}}
env = XCURSOR_THEME,{{cursor_theme_name}}

unbind = $mod, Q

bind = $mod SHIFT, F, exec, firefox
bind = $mod, Q, exec, alacritty
bind = $mod, code:107, exec, hyprshot -m region --freeze --clipboard-only