env = HYPRCURSOR_THEME,{{cursor_theme_name}}
env = XCURSOR_THEME,{{cursor_theme_name}}

exec-once = quickshell

bind = $mainMod SHIFT, F, exec, firefox
bind = $mainMod, code:107, exec, hyprshot -m region --freeze --clipboard-only
