# Shell variables
# Generated by 'wal'
wallpaper='/home/lex/Pictures/wallpapers/wallpaper_8.png'

# Special
background='#22102a'
foreground='#f5e0d0'
cursor='#f5e0d0'

# Colors
color0='#22102a'
color1='#8E3987'
color2='#AD6A8F'
color3='#D66A8E'
color4='#D18C96'
color5='#EAA39E'
color6='#E1C1B3'
color7='#f5e0d0'
color8='#ab9c91'
color9='#8E3987'
color10='#AD6A8F'
color11='#D66A8E'
color12='#D18C96'
color13='#EAA39E'
color14='#E1C1B3'
color15='#f5e0d0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
