{
  lib,
  helpers,
  theme,
}: let
  gtk = helpers.mkGtkTheme {inherit theme;};
  qt = helpers.mkQtTheme {inherit theme;};
  firefox = helpers.mkFirefoxTheme {inherit theme;};
  tokens = helpers.mkThemeTokens {inherit qt theme;};

  roles = helpers.mkThemeRoles theme;
  t = helpers.mkThemePalette theme;
in {
  inherit (tokens) dotfileSubstitutions sessionVariables;

  paletteJson = builtins.toJSON {
    name = theme.name;
    gtk = theme.gtk.name;
    icon = theme.icon.name;
    cursor = {
      name = theme.cursor.name;
      size = theme.cursor.size;
    };
    font = theme.font;
    ui = theme.ui;
    inherit roles;
    qt = {
      platformTheme = qt.platformTheme;
      style = qt.style;
      qtctStyle = qt.qtctStyle;
      kvantum = qt.kvantumTheme;
      colorScheme = qt.colorSchemeName;
    };
    kitty = theme.apps.kitty;
  };

  paletteShell = lib.concatLines (
    ["# generated by Nix"]
    ++ lib.mapAttrsToList (
      name: value: "export ${name}=${lib.escapeShellArg value}"
    )
    tokens.sessionVariables
  );

  dconfSettings = gtk.dconfSettings;
  gtk2Rc = gtk.gtk2Rc;
  gtk3Settings = gtk.gtkSettings;
  gtk4Settings = gtk.gtkSettings;
  gtk3Css = gtk.gtk3Css;
  gtk4Css = gtk.gtk4Css;
  gtk3DarkCss = gtk.gtk3Css;
  gtk4DarkCss = gtk.gtk4Css;

  kvantumConfig = qt.kvantumConfig;
  kdeGlobals = qt.kdeGlobals;
  kdeColorScheme = qt.kdeColorScheme;
  kdeColorSchemeFileName = qt.colorSchemeFileName;
  qt5ctConfig = qt.qt5ctConfig;
  qt6ctConfig = qt.qt6ctConfig;
  qtctColorScheme = qt.qtctColorScheme;
  qtctColorSchemeFileName = qt.qtctColorSchemeFileName;

  environmentVariables = {
    GTK_THEME = theme.gtk.name;
    GTK2_RC_FILES = "/etc/gtk-2.0/gtkrc";
    QT_QPA_PLATFORMTHEME = qt.platformTheme;
    QT_STYLE_OVERRIDE = qt.style;
    XCURSOR_THEME = theme.cursor.name;
    XCURSOR_SIZE = toString theme.cursor.size;
  };

  kittyTheme = helpers.mkKittyTheme theme.apps.kitty;

  sharePickerQss = ''
    QWidget {
      background-color: ${t.bg};
      color: ${t.fg};
      selection-background-color: ${t.selectionBg};
      selection-color: ${t.selectionFg};
    }
    QLabel {
      color: ${t.fg};
    }
    QFrame, QGroupBox {
      border-color: ${t.border};
    }
    QLineEdit, QComboBox, QListView, QTreeView {
      background-color: ${t.inputBg};
      color: ${t.fg};
      border: 1px solid ${t.border};
      border-radius: 6px;
      padding: 5px 8px;
      selection-background-color: ${t.selectionBg};
      selection-color: ${t.selectionFg};
    }
    QLineEdit:focus, QComboBox:focus, QListView:focus, QTreeView:focus {
      border-color: ${t.focus};
    }
    QListView::item, QTreeView::item {
      min-height: 24px;
      padding: 4px 8px;
    }
    QListView::item:hover, QTreeView::item:hover {
      background-color: ${t.hoverBg};
    }
    QListView::item:selected, QTreeView::item:selected {
      background-color: ${t.selectionBg};
      color: ${t.selectionFg};
    }
    QPushButton {
      background-color: ${t.surface};
      color: ${t.fg};
      border: 1px solid ${t.border};
      border-radius: 6px;
      padding: 6px 16px;
    }
    QPushButton:hover {
      background-color: ${t.hoverBg};
      border-color: ${t.borderStrong};
    }
    QPushButton:pressed, QPushButton:checked {
      background-color: ${t.selectionBg};
      color: ${t.selectionFg};
      border-color: ${t.selectionBg};
    }
    QPushButton:disabled {
      color: ${t.disabledFg};
      border-color: ${t.border};
    }
  '';

  firefoxProfilesIni = firefox.profilesIni;
  firefoxUserJs = firefox.userJs;
  firefoxUserContent = firefox.userContent;
  firefoxUserChrome = firefox.userChrome;

  codium = import ./codium {
    inherit theme;
    palette = t;
  };
}
