{
  lib,
  helpers,
  theme,
}: let
  gtk = helpers.mkGtkTheme {inherit theme;};
  qt = helpers.mkQtTheme {inherit theme;};
  firefox = helpers.mkFirefoxTheme {inherit theme;};
  tokens = helpers.mkThemeTokens {inherit qt theme;};

  t = theme.ui;
in {
  inherit (tokens) dotfileSubstitutions sessionVariables;

  paletteJson = builtins.toJSON {
    name = theme.name;
    gtk = theme.gtk.name;
    icon = theme.icon.name;
    cursor = {
      name = theme.cursor.name;
      size = theme.cursor.size;
    };
    font = theme.font;
    ui = theme.ui;
    qt = {
      platformTheme = qt.platformTheme;
      style = qt.style;
      qtctStyle = qt.qtctStyle;
      kvantum = qt.kvantumTheme;
      colorScheme = qt.colorSchemeName;
    };
    kitty = theme.kitty;
  };

  paletteShell = lib.concatLines (
    ["# generated by Nix"]
    ++ lib.mapAttrsToList (
      name: value: "export ${name}=${lib.escapeShellArg value}"
    )
    tokens.sessionVariables
  );

  dconfSettings = gtk.dconfSettings;
  gtk2Rc = gtk.gtk2Rc;
  gtk3Settings = gtk.gtkSettings;
  gtk4Settings = gtk.gtkSettings;
  gtk3Css = gtk.gtk3Css;
  gtk4Css = gtk.gtk4Css;
  gtk3DarkCss = gtk.gtk3Css;
  gtk4DarkCss = gtk.gtk4Css;

  kvantumConfig = qt.kvantumConfig;
  kdeGlobals = qt.kdeGlobals;
  kdeColorScheme = qt.kdeColorScheme;
  kdeColorSchemeFileName = qt.colorSchemeFileName;
  qt5ctConfig = qt.qt5ctConfig;
  qt6ctConfig = qt.qt6ctConfig;
  qtctColorScheme = qt.qtctColorScheme;
  qtctColorSchemeFileName = qt.qtctColorSchemeFileName;

  environmentVariables = {
    GTK_THEME = theme.gtk.name;
    GTK2_RC_FILES = "/etc/gtk-2.0/gtkrc";
    QT_QPA_PLATFORMTHEME = qt.platformTheme;
    QT_STYLE_OVERRIDE = qt.style;
    XCURSOR_THEME = theme.cursor.name;
    XCURSOR_SIZE = toString theme.cursor.size;
  };

  kittyTheme = ''
    background ${theme.kitty.background}
    foreground ${theme.kitty.foreground}
    cursor ${theme.kitty.cursor}
    cursor_text_color ${theme.kitty.cursorText}
    selection_background ${theme.kitty.selection}
    selection_foreground ${theme.kitty.selectionFg}
    url_color ${theme.kitty.url}

    active_tab_background ${theme.kitty.tab.activeBg}
    active_tab_foreground ${theme.kitty.tab.activeFg}
    inactive_tab_background ${theme.kitty.tab.inactiveBg}
    inactive_tab_foreground ${theme.kitty.tab.inactiveFg}

    color0 ${theme.kitty.normal.black}
    color1 ${theme.kitty.normal.red}
    color2 ${theme.kitty.normal.green}
    color3 ${theme.kitty.normal.yellow}
    color4 ${theme.kitty.normal.blue}
    color5 ${theme.kitty.normal.magenta}
    color6 ${theme.kitty.normal.cyan}
    color7 ${theme.kitty.normal.white}
    color8 ${theme.kitty.bright.black}
    color9 ${theme.kitty.bright.red}
    color10 ${theme.kitty.bright.green}
    color11 ${theme.kitty.bright.yellow}
    color12 ${theme.kitty.bright.blue}
    color13 ${theme.kitty.bright.magenta}
    color14 ${theme.kitty.bright.cyan}
    color15 ${theme.kitty.bright.white}
  '';

  sharePickerQss = ''
    QWidget {
      background-color: ${t.bg};
      color: ${t.fg};
    }
    QLabel {
      color: ${t.fg};
    }
    QPushButton {
      background-color: ${t.surface};
      color: ${t.fg};
      border: 1px solid ${t.overlay};
      border-radius: 6px;
      padding: 6px 16px;
    }
    QPushButton:hover {
      background-color: ${t.overlay};
    }
    QPushButton:pressed, QPushButton:checked {
      background-color: ${t.accent};
      color: ${t.bg};
      border-color: ${t.accent};
    }
  '';

  firefoxProfilesIni = firefox.profilesIni;
  firefoxUserJs = firefox.userJs;
  firefoxUserContent = firefox.userContent;
  firefoxUserChrome = firefox.userChrome;

  codium = import ./codium {inherit theme;};
}
