{
  lib,
  helpers,
  theme,
}: let
  gtk = helpers.mkGtkTheme {inherit theme;};
  qt = helpers.mkQtTheme {inherit theme;};
  firefox = helpers.mkFirefoxTheme {inherit theme;};

  sessionVariables = {
    GTK_THEME = theme.gtk.name;
    THEME_NAME = theme.name;
    THEME_GTK = theme.gtk.name;
    THEME_ICON = theme.icon.name;
    THEME_CURSOR = theme.cursor.name;
    THEME_CURSOR_SIZE = toString theme.cursor.size;
    THEME_BG = theme.ui.bg;
    THEME_BG_DARK = theme.ui.bgDark;
    THEME_BG_DARKER = theme.ui.bgDarker;
    THEME_SURFACE = theme.ui.surface;
    THEME_OVERLAY = theme.ui.overlay;
    THEME_FG = theme.ui.fg;
    THEME_FG_MUTED = theme.ui.fgMuted;
    THEME_ACCENT = theme.ui.accent;
    THEME_ACCENT_ALT = theme.ui.accentAlt;
    THEME_ACCENT_BRIGHT = theme.ui.accentBright;
    THEME_SHADOW = theme.ui.shadow;
    THEME_RED = theme.ui.red;
    THEME_GREEN = theme.ui.green;
    THEME_YELLOW = theme.ui.yellow;
    THEME_BLUE = theme.ui.blue;
    THEME_CYAN = theme.ui.cyan;
    PROMPT_COLOR = helpers.promptColorFor theme;
  };

  dotfileSubstitutions = {
    "{{gtk_theme}}" = theme.gtk.name;
    "{{icon_theme}}" = theme.icon.name;
    "{{cursor_theme}}" = theme.cursor.name;
    "{{cursor_theme_name}}" = theme.cursor.name;
    "{{cursor_size}}" = toString theme.cursor.size;
    "{{font_sans}}" = theme.font.sans;
    "{{font_document}}" = theme.font.document;
    "{{font_mono}}" = theme.font.mono;
    "{{ui_bg}}" = theme.ui.bg;
    "{{ui_bg_hex}}" = helpers.stripHex theme.ui.bg;
    "{{ui_bg_dark}}" = theme.ui.bgDark;
    "{{ui_bg_dark_hex}}" = helpers.stripHex theme.ui.bgDark;
    "{{ui_bg_darker}}" = theme.ui.bgDarker;
    "{{ui_bg_darker_hex}}" = helpers.stripHex theme.ui.bgDarker;
    "{{ui_surface}}" = theme.ui.surface;
    "{{ui_surface_hex}}" = helpers.stripHex theme.ui.surface;
    "{{ui_overlay}}" = theme.ui.overlay;
    "{{ui_overlay_hex}}" = helpers.stripHex theme.ui.overlay;
    "{{ui_fg}}" = theme.ui.fg;
    "{{ui_fg_hex}}" = helpers.stripHex theme.ui.fg;
    "{{ui_fg_muted}}" = theme.ui.fgMuted;
    "{{ui_fg_muted_hex}}" = helpers.stripHex theme.ui.fgMuted;
    "{{ui_accent}}" = theme.ui.accent;
    "{{ui_accent_hex}}" = helpers.stripHex theme.ui.accent;
    "{{ui_accent_alt}}" = theme.ui.accentAlt;
    "{{ui_accent_alt_hex}}" = helpers.stripHex theme.ui.accentAlt;
    "{{ui_accent_bright}}" = theme.ui.accentBright;
    "{{ui_accent_bright_hex}}" = helpers.stripHex theme.ui.accentBright;
    "{{ui_shadow}}" = theme.ui.shadow;
    "{{ui_shadow_hex}}" = helpers.stripHex theme.ui.shadow;
    "{{ui_red}}" = theme.ui.red;
    "{{ui_green}}" = theme.ui.green;
    "{{ui_yellow}}" = theme.ui.yellow;
    "{{ui_blue}}" = theme.ui.blue;
    "{{ui_cyan}}" = theme.ui.cyan;
    "{{qt_platform_theme}}" = qt.platformTheme;
    "{{qt_style}}" = qt.style;
    "{{quickshell_primary}}" = theme.ui.surface;
    "{{quickshell_secondary}}" = theme.ui.accent;
    "{{quickshell_secondary_bright}}" = theme.ui.accentBright;
  };

  t = theme.ui;
in {
  inherit dotfileSubstitutions sessionVariables;

  paletteJson = builtins.toJSON {
    name = theme.name;
    gtk = theme.gtk.name;
    icon = theme.icon.name;
    cursor = {
      name = theme.cursor.name;
      size = theme.cursor.size;
    };
    font = theme.font;
    ui = theme.ui;
    qt = {
      platformTheme = qt.platformTheme;
      style = qt.style;
      qtctStyle = qt.qtctStyle;
      kvantum = qt.kvantumTheme;
      colorScheme = qt.colorSchemeName;
    };
    kitty = theme.kitty;
  };

  paletteShell = lib.concatLines (
    ["# generated by Nix"]
    ++ lib.mapAttrsToList (
      name: value: "export ${name}=${lib.escapeShellArg value}"
    )
    sessionVariables
  );

  dconfSettings = gtk.dconfSettings;
  gtk2Rc = gtk.gtk2Rc;
  gtk3Settings = gtk.gtkSettings;
  gtk4Settings = gtk.gtkSettings;
  gtk3Css = gtk.gtk3Css;
  gtk4Css = gtk.gtk4Css;
  gtk3DarkCss = gtk.gtk3Css;
  gtk4DarkCss = gtk.gtk4Css;

  kvantumConfig = qt.kvantumConfig;
  kdeGlobals = qt.kdeGlobals;
  kdeColorScheme = qt.kdeColorScheme;
  kdeColorSchemeFileName = qt.colorSchemeFileName;
  qt5ctConfig = qt.qt5ctConfig;
  qt6ctConfig = qt.qt6ctConfig;
  qtctColorScheme = qt.qtctColorScheme;
  qtctColorSchemeFileName = qt.qtctColorSchemeFileName;

  environmentVariables = {
    GTK_THEME = theme.gtk.name;
    GTK2_RC_FILES = "/etc/gtk-2.0/gtkrc";
    QT_QPA_PLATFORMTHEME = qt.platformTheme;
    QT_STYLE_OVERRIDE = qt.style;
    XCURSOR_THEME = theme.cursor.name;
    XCURSOR_SIZE = toString theme.cursor.size;
  };

  kittyTheme = ''
    background ${theme.kitty.background}
    foreground ${theme.kitty.foreground}
    cursor ${theme.kitty.cursor}
    cursor_text_color ${theme.kitty.cursorText}
    selection_background ${theme.kitty.selection}
    selection_foreground ${theme.kitty.selectionFg}
    url_color ${theme.kitty.url}

    active_tab_background ${theme.kitty.tab.activeBg}
    active_tab_foreground ${theme.kitty.tab.activeFg}
    inactive_tab_background ${theme.kitty.tab.inactiveBg}
    inactive_tab_foreground ${theme.kitty.tab.inactiveFg}

    color0 ${theme.kitty.normal.black}
    color1 ${theme.kitty.normal.red}
    color2 ${theme.kitty.normal.green}
    color3 ${theme.kitty.normal.yellow}
    color4 ${theme.kitty.normal.blue}
    color5 ${theme.kitty.normal.magenta}
    color6 ${theme.kitty.normal.cyan}
    color7 ${theme.kitty.normal.white}
    color8 ${theme.kitty.bright.black}
    color9 ${theme.kitty.bright.red}
    color10 ${theme.kitty.bright.green}
    color11 ${theme.kitty.bright.yellow}
    color12 ${theme.kitty.bright.blue}
    color13 ${theme.kitty.bright.magenta}
    color14 ${theme.kitty.bright.cyan}
    color15 ${theme.kitty.bright.white}
  '';

  sharePickerQss = ''
    QWidget {
      background-color: ${t.bg};
      color: ${t.fg};
    }
    QLabel {
      color: ${t.fg};
    }
    QPushButton {
      background-color: ${t.surface};
      color: ${t.fg};
      border: 1px solid ${t.overlay};
      border-radius: 6px;
      padding: 6px 16px;
    }
    QPushButton:hover {
      background-color: ${t.overlay};
    }
    QPushButton:pressed, QPushButton:checked {
      background-color: ${t.accent};
      color: ${t.bg};
      border-color: ${t.accent};
    }
  '';

  firefoxProfilesIni = firefox.profilesIni;
  firefoxUserJs = firefox.userJs;
  firefoxUserContent = firefox.userContent;
  firefoxUserChrome = firefox.userChrome;

  codium = import ./codium {inherit theme;};
}
