export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

export HISTFILE="${HISTFILE:-$XDG_STATE_HOME/bash/history}"
export LESSHISTFILE="${LESSHISTFILE:-$XDG_STATE_HOME/less/history}"
export CARGO_HOME="${CARGO_HOME:-$XDG_DATA_HOME/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$XDG_DATA_HOME/rustup}"
export GOPATH="${GOPATH:-$XDG_DATA_HOME/go}"
export NPM_CONFIG_USERCONFIG="${NPM_CONFIG_USERCONFIG:-$XDG_CONFIG_HOME/npm/npmrc}"
export NPM_CONFIG_CACHE="${NPM_CONFIG_CACHE:-$XDG_CACHE_HOME/npm}"
export NPM_CONFIG_INIT_MODULE="${NPM_CONFIG_INIT_MODULE:-$XDG_CONFIG_HOME/npm/config/npm-init.js}"
export NPM_CONFIG_TMP="${NPM_CONFIG_TMP:-${XDG_RUNTIME_DIR:-/tmp}/npm}"
export DOCKER_CONFIG="${DOCKER_CONFIG:-$XDG_CONFIG_HOME/docker}"
export GNUPGHOME="${GNUPGHOME:-$XDG_DATA_HOME/gnupg}"
export WGETRC="${WGETRC:-$XDG_CONFIG_HOME/wget/wgetrc}"
export NODE_REPL_HISTORY="${NODE_REPL_HISTORY:-$XDG_STATE_HOME/node/repl_history}"
export PYTHON_HISTORY="${PYTHON_HISTORY:-$XDG_STATE_HOME/python_history}"
export GRADLE_USER_HOME="${GRADLE_USER_HOME:-$XDG_DATA_HOME/gradle}"
export DOTNET_CLI_HOME="${DOTNET_CLI_HOME:-$XDG_DATA_HOME/dotnet}"
export NUGET_PACKAGES="${NUGET_PACKAGES:-$XDG_CACHE_HOME/nuget}"
export CUDA_CACHE_PATH="${CUDA_CACHE_PATH:-$XDG_CACHE_HOME/nv}"
export WAKATIME_HOME="${WAKATIME_HOME:-$XDG_CONFIG_HOME/wakatime}"
export _JAVA_OPTIONS="${_JAVA_OPTIONS:--Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java -Djavafx.cachedir=$XDG_CACHE_HOME/openjfx}"
export CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-$XDG_CONFIG_HOME/claude}"
export CODEX_HOME="${CODEX_HOME:-$XDG_CONFIG_HOME/codex}"

mkdir -p \
    "$XDG_STATE_HOME/bash" \
    "$XDG_STATE_HOME/less" \
    "$XDG_STATE_HOME/node" \
    "$XDG_CACHE_HOME/npm" \
    "$XDG_CONFIG_HOME/npm/config"

if [ -f "$HOME/.config/theme/palette.sh" ]; then
    . "$HOME/.config/theme/palette.sh"
fi

PROMPT_COLOR="${PROMPT_COLOR:-95m}"
export PS1="\n\[\033[$PROMPT_COLOR\][\u@\h:\w]\\$\[\033[0m\] "

alias battery-info="upower -i /org/freedesktop/UPower/devices/battery_BAT0"
alias battery="upower -i /org/freedesktop/UPower/devices/battery_BAT0"

alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"

alias ls="eza --icons --git --group-directories-first"
alias l="eza -la --icons --git --group-directories-first"
alias tree="eza --tree --icons --git --group-directories-first"

wifi_full_restart () {
    sudo ip link set wlo1 down
    sudo rfkill unblock wlan
    sudo ip link set wlo1 up
    sudo systemctl restart NetworkManager
}

gpu () {
    __NV_PRIME_RENDER_OFFLOAD=1 \
    __GLX_VENDOR_LIBRARY_NAME=nvidia \
    "$@"
}

eval "$(direnv hook bash)"
LC_COLLATE=C
